name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      build_files: ${{ steps.filter.outputs.build_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for changes in build-related files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            build_files:
              - 'Dockerfile'
              - 'main.py'
              - 'poetry.lock'
              - 'src/**'

  build-and-push:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.build_files == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: echo "Building Docker image..."
      - name: Push Docker image to Azure Container Registry
        run: echo "Pushing Docker image to ACR..."
