name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  changes: 
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          Dockerfile
          main.py
          poetry.lock

  build-and-push:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: echo "Building Docker image..."
      - name: Push Docker image to Azure Container Registry
        run: echo "Pushing Docker image to ACR..."