name: Detect Changes

on:
  workflow_call:
    outputs:
      build_files:
        description: "Indicates if build-related files have changed"
        value: ${{ jobs.detect-build-changes.outputs.build_files }}
      version:
        description: "Version found in the repository"
        value: ${{ jobs.get-version.outputs.version }}

jobs:
  detect-build-changes:
    runs-on: ubuntu-latest
    outputs:
      build_files: ${{ steps.filter.outputs.build_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check for changes in build-related files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            build_files:
              - 'Dockerfile'
              - 'main.py'
              - 'poetry.lock'
              - 'src/**'

  get-version:
    needs: detect-version-changes
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version
        id: set_version
        run: |
          if [ "${{ needs.detect-version-changes.outputs.version_file_changed }}" == 'true' ]; then
            if [ -f build.info ]; then
              version=$(cat build.info)
              echo "version=$version" >> $GITHUB_OUTPUT
            else
              echo "Error: build.info does not exist."
              exit 1
            fi
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      
