name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  detect-changes:
    needs: 
      - ci
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
    uses: ./.github/workflows/detect-changes.yaml

  build:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.build_files == 'true' || needs.detect-changes.outputs.version != 'latest' }}
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      version: ${{ needs.detect-changes.outputs.version }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.build.outputs.version }}

  release:
    needs: deploy-prev
    if: ${{ needs.deploy.outputs.deploy_prev_success == 'true' }}
    uses: ./.github/workflows/release.yaml
    with:
      version: ${{ needs.deploy.outputs.version }}
