name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

  build:
    needs: ci
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

  deploy:
    needs: build
    if: success()
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}