name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    needs: ci
    if: needs.ci.outputs.build_required == 'true'
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

  deploy:
    needs: build
    if: success()
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}