name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  detect-changes:
    needs: 
      - ci
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
    uses: ./.github/workflows/detect_changes.yaml

  build:
    needs: ci
    if: ${{ needs.detect-changes.outputs.build_files == 'true' || needs.detect-changes.outputs.version != 'latest' }}
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.detect-changes.outputs.version}}

  deploy:
    needs: build
    if: success()
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.detect-changes.outputs.version}}

  release:
    needs:
      - detect-changes
      - build
      - deploy
    if: ${{ needs.detect-changes.outputs.version != 'latest' }}
    uses: ./.github/workflows/release.yaml
    with:
      version: ${{ needs.detect-changes.outputs.version}}