name: Release docker images

on:
  release:
    types: [ published ]
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Version
        run: echo "Releasing version: ${{ inputs.version }}"
