name: Release docker images

on:
  release:
    types: [ published ]
  workflow_call:
    inputs:
      version:
        required: true
        type: string 

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Release Application
        run: echo "Releasing version '${{ needs.deploy-prev.outputs.version }}'"
